name: bb_pos
description: "POS Systems."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  go_router: ^16.2.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  uuid: ^4.5.1
  path: ^1.9.1
  get_it: ^8.2.0
  unicons: ^3.0.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7
  google_fonts: ^6.3.0
  gap: ^3.0.1
  currency_text_input_formatter: ^2.3.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/hot-air-balloon.png
    - assets/images/FATAL Error 3 Streamline Barcelona.png
    - assets/images/Food Menu Streamline Milano.png